# 02: Retrieval Evaluation

In [ ]:
from carryia.pipeline.ingest import load_corpus, build_text_index, build_vector_index
from carryia.eval.eval_retrieval import (
    load_ground_truth,
    keyword_retriever,
    vector_retriever,
    hybrid_retriever,
    relevance_matrix,
    hit_rate,
    mrr,
    find_misses,
    build_gold_sets,
)

documents = load_corpus()
ground_truth = load_ground_truth()

len(documents), len(ground_truth)

In [2]:
by_id = {doc["tip_id"]: doc for doc in documents}

## Keyword retriever

The metrics and adapters are imported from `eval_retrieval.py` (unit-tested
there); the corpus and both indexes come from stage ⑤'s `ingest.py`.

In [3]:
keyword_index = build_text_index(documents)
keyword = keyword_retriever(keyword_index, k=5)

In [4]:
q = ground_truth[0]
q["question"]

"Why do I keep getting caught out in lane when I feel like I should've seen them coming?"

In [5]:
[by_id[tip_id]["tip"] for tip_id in keyword(q["question"])]

["Place wards in known ambush 'kill zones' to avoid getting caught out, especially against assassins or mages.",
 'Deep wards let you catch the enemy rotating and free your fed player to split-push aggressively, since threats can be seen coming.',
 "When sieging on a squishy composition, don't place deep wards alone — getting caught out solo can ruin the whole siege for the team.",
 'When the enemy carry is alone in lane, you can walk up and harass them or try to keep them out of XP range of their minions.',
 "Place a ward in the middle of your own lane — it tells your team whether you've roamed, recalled, or gone for blue buff, and warns of enemies coming to siege your tower."]

In [6]:
q["seed_tip_id"] in keyword(q["question"])

False

## Score it

`relevance_matrix` runs the retriever over every question and marks the rank
of the seed tip; `hit_rate` and `mrr` roll that up (course `search.ipynb`
technique).

In [7]:
relevance_matrix(keyword, ground_truth[:5])

[[False, False, False, False, False],
 [False, False, False, False, False],
 [False, False, False, False, False],
 [False, False, False, False, False],
 [False, False, False, False, False]]

In [8]:
relevance = relevance_matrix(keyword, ground_truth)

hit_rate(relevance), mrr(relevance)

(0.2383638928067701, 0.15639398213446168)

In [9]:
import pandas as pd

def evaluate(name, retriever):
    relevance = relevance_matrix(retriever, ground_truth)
    return {
        "approach": name,
        "hit_rate": hit_rate(relevance),
        "mrr": mrr(relevance),
    }

results = [evaluate("keyword", keyword)]

pd.DataFrame(results)

  approach  hit_rate       mrr
0  keyword  0.238364  0.156394

## Vector retriever

Same `Retriever` contract over stage ⑤'s vector index (local `fastembed`
embeddings). First run downloads the pinned model; still no API key.

In [10]:
vector_index = build_vector_index(documents)
vector = vector_retriever(vector_index, k=5)

/Users/mattheworga/Documents/dev/Carryia/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
results.append(evaluate("vector", vector))

pd.DataFrame(results)

  approach  hit_rate       mrr
0  keyword  0.238364  0.156394
1   vector  0.327221  0.222167

## Inspect the misses

Single-seed gold: a question only "hits" if retrieval returns its one
seeding tip. Read the misses — is the top result a near-duplicate of the
seed (gold too narrow → widen to set-based) or genuinely off-topic
(retrieval is weak)?

In [12]:
misses = find_misses(keyword, ground_truth)

len(misses), len(misses) / len(ground_truth)

(540, 0.7616361071932299)

In [13]:
for m in misses[:10]:
    top = keyword(m["question"])
    print("Q:   ", m["question"])
    print("seed:", by_id[m["seed_tip_id"]]["tip"])
    print("got: ", by_id[top[0]]["tip"] if top else "(nothing)")
    print()

Q:    Why do I keep getting caught out in lane when I feel like I should've seen them coming?
seed: Take the Warding Totem (yellow trinket) as your starting trinket in the majority of matchups, since it lets you ward your lane in the early game.
got:  Place wards in known ambush 'kill zones' to avoid getting caught out, especially against assassins or mages.

Q:    How come I kept having 2 wards ready to place but I wasn't actually using them to check anything during the game?
seed: Never let your trinket sit capped at two charges — use a ward before you cap out.
got:  When a fight or scenario goes wrong in the late game, first ask yourself how you can survive before anything else.

Q:    why does my team keep losing vision in random spots on the map when I feel like I've been placing wards the whole game?
seed: As support, be extra mindful of the 3-ward trinket cap, since you place wards far more often than any other role and are the one most likely to overcap.
got:  Normal-casting helps you avoid placing wards over walls in spots the enemy can simply walk past for free.

Q:    I keep getting killed or caught out in fights even when I play around my team — is there something I'm missing about map safety that would've helped?
seed: Buy and place Control Wards whenever you have inventory space — they are worth the gold throughout the game.
got:  If you're worried about getting caught 1v1 in the enemy jungle, it's fine to place some Control Wards inside your own jungle instead for safety.

Q:    How come I felt like I had no idea where their team was moving around the map once mid-game hit, even though I had bought that control ward early on?
seed: As support, buy Control Wards frequently and keep replacing them as the game develops rather than resting on your first purchase.
got:  When contesting a major objective, always place dedicated vision on the enemy's side of the map, since that's the direction their approach will come from.

Q:    why do i feel like the enemy jungler always knows when i'm trying to farm that side of the map
seed: As a solo laner, buy a Control Ward early and keep placing new ones as the game continues.
got:  If you know the enemy jungler isn't on a particular side of the map, that side becomes a safer route to roam through.

Q:    how do I know when I actually need to buy a control ward instead of just buying them automatically every time I back
seed: Don't chase a specific vision score number — just keep buying and placing Control Wards throughout the game as the situation calls for it.
got:  If you need to back, try to do it on a cannon wave, since it can't be fully pushed in and tanks 6-7 tower hits, buying time to return before losing minions.

Q:    Why do I feel like I'm always so far behind on damage and survivability compared to the enemy ADC even though I'm not dying much?
seed: Balance ward purchases against your item build — don't buy so many wards that you fall behind on core items and gold.
got:  When pushing to close out the game on the Nexus, prioritize not dying to the defenders over dealing extra damage.

Q:    Why do I keep running out of control wards mid-game when I need them to clear enemy vision in important fights?
seed: Model your Control Ward habits on pros: they don't aim for a score, they place wards reactively when needed, and they always return to lane with at least one Control Ward.
got:  When the enemy carry is alone in lane, you can walk up and harass them or try to keep them out of XP range of their minions.

Q:    why do i feel like i'm wasting my trinket slot by taking the red one at level 1 instead of just keeping my yellow trinket?
seed: Don't take the Oracle Lens (red trinket) at level 1 — the Warding Totem gives more value that early since the Oracle Lens doesn't meaningfully help you or your team yet.
got:  Only Top, Mid, and ADC should pick up the Farsight Alteration (blue trinket) after level 9 — Jungle and Support are better served taking the red trinket instead.

## Set-based gold

The single-seed misses above are mostly near-duplicates of the seed, so the
answer key is too narrow — it demands the one arbitrary seeded id when a
near-dupe is just as correct. `build_gold_sets` widens it: for each tip, the set
of tips within `threshold` cosine on ⑤'s local embeddings counts as correct
(per-seed neighbourhoods, kept tight so no approach saturates to ~1.0). Re-score
both approaches by passing `gold=`.

In [14]:
gold = build_gold_sets(documents, threshold=0.87)

sizes = pd.Series([len(s) for s in gold.values()])
print("set size — mean {:.2f}, median {:.0f}, max {}".format(
    sizes.mean(), sizes.median(), sizes.max()))
print("singletons: {} / {}".format(int((sizes == 1).sum()), len(sizes)))

set size — mean 1.73, median 1, max 15
singletons: 498 / 709

In [15]:
def evaluate(name, retriever, gold=None):
    relevance = relevance_matrix(retriever, ground_truth, gold=gold)
    return {"approach": name, "hit_rate": hit_rate(relevance), "mrr": mrr(relevance)}

pd.DataFrame([
    evaluate("keyword · single-seed", keyword),
    evaluate("vector · single-seed",  vector),
    evaluate("keyword · set@0.87",    keyword, gold),
    evaluate("vector · set@0.87",     vector,  gold),
])

                approach  hit_rate       mrr
0  keyword · single-seed  0.238364  0.156394
1   vector · single-seed  0.327221  0.222167
2     keyword · set@0.87  0.267983  0.171556
3      vector · set@0.87  0.362482  0.257052

### Threshold sensitivity — is the pick robust?

Absolute scores depend on how loose the gold is, so sweep the threshold. If
vector beats keyword across *every* setting, the pick doesn't hinge on an
arbitrary cutoff — that robustness is the graded justification. Looser than
~0.85 over-credits: a single "equivalent" set swells past 100 tips, which isn't
an honest answer key.

In [16]:
sweep = []
for thr in (0.80, 0.85, 0.87, 0.90):
    g = build_gold_sets(documents, threshold=thr)
    sweep.append({
        "threshold": thr,
        "max_set": max(len(s) for s in g.values()),
        "keyword_hit": hit_rate(relevance_matrix(keyword, ground_truth, gold=g)),
        "vector_hit":  hit_rate(relevance_matrix(vector,  ground_truth, gold=g)),
    })
pd.DataFrame(sweep)

   threshold  max_set  keyword_hit  vector_hit
0       0.80      111     0.448519    0.576869
1       0.85       24     0.308886    0.400564
2       0.87       15     0.267983    0.362482
3       0.90        8     0.246827    0.339915

## Are the remaining misses gold-narrowness or weak retrieval?

Set-based@0.87 still misses most questions for vector. Are those genuine
failures, or relevant tips the near-dupe gold doesn't credit? Print the seed and
the top-3 retrieved tips for a sample of set-based misses and read them.

In [17]:
import random

set_misses = [row for row in ground_truth
              if not (gold[row["seed_tip_id"]] & set(vector(row["question"])))]
print(len(set_misses), "/", len(ground_truth), "vector set-based misses\n")

random.seed(7)
for row in random.sample(set_misses, 12):
    ranked = vector(row["question"])
    print("Q:   ", row["question"])
    print("seed:", by_id[row["seed_tip_id"]]["tip"])
    for r, tid in enumerate(ranked[:3], 1):
        print(f"  top{r}:", by_id[tid]["tip"])
    print()

452 / 709 vector set-based misses

Q:    I keep feeling like I'm letting my ADC down when they get caught out—is there a support I should be playing that makes it easier to keep my team alive?
seed: If you want a support who heals, shields, and buffs to keep allies safe, play Milio as a beginner.
  top1: Recognize when you believe your ADC is a lost cause and give up on them to prioritize roaming or playing around stronger teammates instead.
  top2: As ADC, if your support dies, don't push the wave — let it come to you and freeze it outside your tower so your support can recover the XP and CS they missed.
  top3: As support, before roaming to help another lane, make sure your ADC will be safe and won't die while you're gone.

Q:    why do i feel like i'm wasting my early vision wards placing them deep in my own jungle when we're not even under pressure
seed: Don't start deep-warding your own jungle unless forced to, such as when you're behind or facing a strong invader — otherwise prioritize the river and the enemy jungle instead.
  top1: Don't waste wards on the enemy jungle when you're behind — the enemy won't be using their own jungle much since they're busy taking yours, and you risk getting caught out of position placing it.
  top2: For your own jungle's safety, prioritize warding the entrances over placing deep wards, since entrance vision gives your team the earliest possible warning before camps are actually taken.
  top3: Don't waste wards in your own jungle while preparing to siege, since the goal is to make it hard for the enemy to step out.

Q:    Why do I feel like I always get punished whenever I try to roam mid from bot lane?
seed: Ezreal is a good candidate to leave alone while roaming, since his Q and E let him farm safely for a short period.
  top1: Get out of the mindset that roaming always gets your ADC killed.
  top2: If a lane keeps overextending for farm after your first gank, keep roaming back to punish it repeatedly.
  top3: Learn when to break the standard roam-timing rules, which typically means giving up bot lane entirely.

Q:    Why did I feel like I was dying so easily when I was trying to trade with their bot lane?
seed: As a damage-dealer support, take Ignite on shorter-range champions like Brand or Twitch, or Barrier on longer-range champions like Senna or Vel'Koz.
  top1: Avoid slow pushing during the early laning phase, since it can cost you CS and gold and put you in bad trades — save it for the later stages of laning and beyond.
  top2: Take trades where you either deal more damage than you take, or put your opponent in a difficult situation to stay in the lane.
  top3: Time your trades for when the enemy ADC goes to last hit a minion, since they're locked in their attack animation and can't retaliate.

Q:    why do I keep getting caught out when we're pushed way up in lane and the enemy just walks out of their jungle and kills us before we can escape
seed: When ahead and pushed up in lane, ward deeper into the enemy jungle — the further forward you are, the more warning time you need to react to the enemy closing in.
  top1: Get out of the mindset that roaming always gets your ADC killed.
  top2: Don't walk straight into the enemy jungle to place wards once lane phase ends — that's how supports get caught and killed.
  top3: If your jungler invaded and stole an enemy buff, leave the leash by 1:33 at the latest, since you still need to get back to your own lane to avoid falling behind.

Q:    When our mid laner was getting bullied and falling behind, should they have been roaming to help us in bot lane more, or were they making the right call staying in lane?
seed: When behind in mid lane, don't roam or wander the map alone — warding well and taking risk-free trades is the safer path back into the game.
  top1: If your ADC is unreliable, your time is better spent getting your other laners ahead through roaming.
  top2: Before roaming, ask yourself two questions: what am I potentially losing or causing my ADC to lose by being there, and where is the next play most likely going to happen.
  top3: If your ADC can't play safe or tolerate you being gone briefly, roaming is still probably the better use of your time.

Q:    Why do I keep getting picked off or caught when we're trying to finish the game and they have respawn timers that are basically back to zero?
seed: When pushing to close out the game on the Nexus, prioritize not dying to the defenders over dealing extra damage.
  top1: Recall to reset when you still have enough time before the next objective spawns, rather than forcing a fight.
  top2: Once you've set up the other side of the map and the enemy resets from their objective, look for a pick as they try to re-enter.
  top3: Time your return to lane to coincide with the enemy's respawn so you don't miss out on farm, XP, or lane pressure.

Q:    Why does it feel like I'm getting punished whenever I leave lane to help my team, like the enemy just instantly crashes a huge wave into my tower?
seed: Your rebound-roam timer expires once the wave reaches your own turret — be back in lane by then.
  top1: In top lane, fast push the wave before making a Teleport play or helping another lane, since it forces the enemy laner to either miss CS staying in lane or lose the ability to contest your play.
  top2: Don't over-value team comp synergy in solo queue; most of the time other lanes won't come out even and your team won't coordinate well enough in fights for the comp to truly matter.
  top3: Since supports are the only champions still carrying control wards in the later stages of the game, the whole map gets much darker, and you need to play safer accordingly.

Q:    Why do I feel like my wards aren't helping us when we're behind and getting pressured — like I'm placing them too far forward and we're getting caught before we even see the enemy coming?
seed: When losing after laning phase, pull your wards back closer to your own jungle rather than warding evenly or into the enemy jungle, since the fight will mostly happen on your side of the map.
  top1: Ward objectives from further away rather than right on top of them, since more distant wards give you more reaction time to decide whether to fight, take it, or back off.
  top2: When winning, keep applying pressure with strong ward coverage rather than easing off, since failing to keep pressuring the enemy is how you let them back into the game.
  top3: As support, don't go warding alone even though vision is your priority — wait for your team so you're not an easy target for the enemy.

Q:    When the enemy mid laner leaves lane, should I always fall back to protect my team or is it worth chasing them down if I think I can catch them solo?
seed: If you're strong in 1v1s, like on Zed or Akali, directly follow the enemy roamer rather than taking a longer defensive route.
  top1: If your carry needs to back and you don't, use the opportunity to roam mid.
  top2: Ganking the enemy mid laner as support is very strong, since your lockdown and damage are often enough alone to secure the kill.
  top3: After killing your enemy laner (or they've recalled), take the opportunity to roam while your lane is safe.

Q:    Why do we keep getting caught off guard by level one all-ins when we walk into lane — is there something we should be doing earlier to stop that from happening?
seed: Rush to lane at the start of the game and ward the middle bush, whether as ADC or support, to prevent level-one bush cheeses.
  top1: In top lane, fast push the wave before making a Teleport play or helping another lane, since it forces the enemy laner to either miss CS staying in lane or lose the ability to contest your play.
  top2: If you don't need to ward for an invade, drop your level-1 ward in lane instead to avoid a potential level-1 cheese.
  top3: Roam to a lane if an ally there is struggling and falling behind in levels, experience, or gold.

Q:    Why do I keep getting my wards cleared instantly when I'm trying to secure vision in enemy territory while we're ahead?
seed: When winning top lane and pushed into enemy territory, prioritize trinket wards over Control Wards, since the enemy can clear a visible Control Ward there too easily.
  top1: Since wards last up to two and a half minutes, time your vision setup so it's still active when the objective spawns.
  top2: When your team is sieging, put wards deep into the enemy base while denying all vision outside of it.
  top3: Try to destroy enemy wards with auto-attacks before they go invisible whenever you get the chance, rather than ignoring them.

## Hybrid (keyword + vector via RRF)

The miss analysis points at hybrid: BM25 catches lexical overlap the embedding
misses, vector catches paraphrases BM25 misses. `hybrid_retriever` fuses their
rankings with **Reciprocal Rank Fusion** — each tip scored `1/(60+rank)` in each
list, summed, re-sorted — needing only ranks (minsearch exposes ranks, not
comparable scores). Sub-retrievers run deep (k=20); the fused list is truncated
to the top-5 the others report.

In [18]:
hybrid = hybrid_retriever(
    [keyword_retriever(keyword_index, k=20),
     vector_retriever(vector_index, k=20)],
    k=5,
)

pd.DataFrame([
    evaluate("keyword · single-seed", keyword),
    evaluate("vector · single-seed",  vector),
    evaluate("hybrid · single-seed",  hybrid),
    evaluate("keyword · set@0.87",    keyword, gold),
    evaluate("vector · set@0.87",     vector,  gold),
    evaluate("hybrid · set@0.87",     hybrid,  gold),
])

                approach  hit_rate       mrr
0  keyword · single-seed  0.238364  0.156394
1   vector · single-seed  0.327221  0.222167
2   hybrid · single-seed  0.354020  0.240268
3     keyword · set@0.87  0.267983  0.171556
4      vector · set@0.87  0.362482  0.257052
5      hybrid · set@0.87  0.392102  0.269864

## Conclusion

- **Ranking is consistent and robust — hybrid > vector > keyword**, on both
  hit-rate and MRR, at both gold definitions. Vector beats keyword at every
  threshold in the sweep, and hybrid (RRF of the two) tops both: set@0.87 hit
  .392 / MRR .270 vs vector .362 / .257. The pick doesn't hinge on the gold
  definition, which is exactly what P0-5 grades.
- **Set-based gold roughly doubles the absolute scores** vs single-seed without
  saturating — the low single-seed numbers were mostly a near-duplicate artifact,
  not weak retrieval (~70% of set-based misses surface a genuinely relevant
  non-dupe tip; the real failures cluster on hyper-specific champion/item seeds).
- **Hybrid's edge is modest (~8% over vector) but real** — consistent with
  indexing `tip` only, so BM25 lacks the champion/item vocabulary that lives in
  `source_excerpt`. Adding `source_excerpt` to the keyword
  text fields ("reversible in one line") would likely widen the gap — the next
  lever, alongside re-ranking.
- **Pick: hybrid** (RRF of keyword + vector), with vector as the strong
  single-approach baseline.